# /bin/bash

../python/main.py train ../Data/training/train.csv         -vectorize_method BOW-LDA -n_dim 50         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle
../python/main.py predict ../Data/training/train.csv         -vectorize_method BOW-LDA         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle         -cluster_dist test         -path_out ../Data/training/train_BOW-LDA_hierarch_cosine_average_cluster_purity.csv
../python/main.py predict ../Data/training/test.csv         -vectorize_method BOW-LDA         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle         -cluster_dist test         -path_out ../Data/training/test_BOW-LDA_hierarch_cosine_average_cluster_purity.csv
../python/main.py train ../Data/training/train.csv         -vectorize_method BOW-LDA -n_dim 50         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle
../python/main.py predict ../Data/training/train.csv         -vectorize_method BOW-LDA         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle         -cluster_dist test         -path_out ../Data/training/train_BOW-LDA_hierarch_euclid_ward_cluster_purity.csv
../python/main.py predict ../Data/training/test.csv         -vectorize_method BOW-LDA         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_BOW-LDA.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle         -cluster_dist test         -path_out ../Data/training/test_BOW-LDA_hierarch_euclid_ward_cluster_purity.csv
../python/main.py train ../Data/training/train.csv         -vectorize_method word2vec -n_dim 50         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle
../python/main.py predict ../Data/training/train.csv         -vectorize_method word2vec         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle         -cluster_dist test         -path_out ../Data/training/train_word2vec_hierarch_cosine_average_cluster_purity.csv
../python/main.py predict ../Data/training/test.csv         -vectorize_method word2vec         -cluster_method  hierarch_cosine_average        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_cosine_average.pickle         -cluster_dist test         -path_out ../Data/training/test_word2vec_hierarch_cosine_average_cluster_purity.csv
../python/main.py train ../Data/training/train.csv         -vectorize_method word2vec -n_dim 50         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle
../python/main.py predict ../Data/training/train.csv         -vectorize_method word2vec         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle         -cluster_dist test         -path_out ../Data/training/train_word2vec_hierarch_euclid_ward_cluster_purity.csv
../python/main.py predict ../Data/training/test.csv         -vectorize_method word2vec         -cluster_method  hierarch_euclid_ward        -path_model ../Data/training/train_model_vectorize_word2vec.pickle,../Data/training/train_model_cluster_hierarch_euclid_ward.pickle         -cluster_dist test         -path_out ../Data/training/test_word2vec_hierarch_euclid_ward_cluster_purity.csv
